# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bqip/v1/common.proto
# Protobuf Python Version: 6.33.6
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    6,
    '',
    'bqip/v1/common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x62qip/v1/common.proto\x12\x07\x62qip.v1\"V\n\x0c\x44\x65\x63imalValue\x12\x18\n\x0b\x63oefficient\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x12\n\x05scale\x18\x02 \x01(\rH\x01\x88\x01\x01\x42\x0e\n\x0c_coefficientB\x08\n\x06_scale\"s\n\tCaptureId\x12\"\n\x15\x63ollector_instance_id\x18\x01 \x01(\x0cH\x00\x88\x01\x01\x12\x18\n\x0b\x63\x61pture_seq\x18\x02 \x01(\x04H\x01\x88\x01\x01\x42\x18\n\x16_collector_instance_idB\x0e\n\x0c_capture_seq\"\x8e\x02\n\x11ProcessingContext\x12$\n\x17processing_timestamp_ns\x18\x01 \x01(\x03H\x00\x88\x01\x01\x12\x18\n\x0b\x63ode_commit\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x1b\n\x0eschema_version\x18\x03 \x01(\rH\x02\x88\x01\x01\x12\x13\n\x06run_id\x18\x04 \x01(\x0cH\x03\x88\x01\x01\x12-\n\x0breplay_mode\x18\x05 \x01(\x0e\x32\x13.bqip.v1.ReplayModeH\x04\x88\x01\x01\x42\x1a\n\x18_processing_timestamp_nsB\x0e\n\x0c_code_commitB\x11\n\x0f_schema_versionB\t\n\x07_run_idB\x0e\n\x0c_replay_mode*\x87\x01\n\nReplayMode\x12\x17\n\x13REPLAY_MODE_UNKNOWN\x10\x00\x12\x14\n\x10REPLAY_MODE_LIVE\x10\x01\x12\'\n#REPLAY_MODE_VERSION_PINNED_RESEARCH\x10\x02\x12!\n\x1dREPLAY_MODE_AS_LIVED_FORENSIC\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bqip.v1.common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REPLAYMODE']._serialized_start=512
  _globals['_REPLAYMODE']._serialized_end=647
  _globals['_DECIMALVALUE']._serialized_start=33
  _globals['_DECIMALVALUE']._serialized_end=119
  _globals['_CAPTUREID']._serialized_start=121
  _globals['_CAPTUREID']._serialized_end=236
  _globals['_PROCESSINGCONTEXT']._serialized_start=239
  _globals['_PROCESSINGCONTEXT']._serialized_end=509
# @@protoc_insertion_point(module_scope)
