# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bqip/v1/manifests.proto
# Protobuf Python Version: 6.33.6
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    6,
    '',
    'bqip/v1/manifests.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x62qip/v1/manifests.proto\x12\x07\x62qip.v1\"\xce\x01\n\x10ManifestEnvelope\x12\x1b\n\x0eschema_version\x18\x01 \x01(\rH\x00\x88\x01\x01\x12 \n\x13\x63\x61nonical_body_json\x18\x02 \x01(\x0cH\x01\x88\x01\x01\x12\x1a\n\rmanifest_hash\x18\x03 \x01(\x0cH\x02\x88\x01\x01\x12\x15\n\x08\x63omments\x18\x04 \x01(\tH\x03\x88\x01\x01\x42\x11\n\x0f_schema_versionB\x16\n\x14_canonical_body_jsonB\x10\n\x0e_manifest_hashB\x0b\n\t_commentsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bqip.v1.manifests_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MANIFESTENVELOPE']._serialized_start=37
  _globals['_MANIFESTENVELOPE']._serialized_end=243
# @@protoc_insertion_point(module_scope)
