# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bqip/v1/metadata.proto
# Protobuf Python Version: 6.33.6
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    6,
    '',
    'bqip/v1/metadata.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from bqip.v1 import common_pb2 as bqip_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x62qip/v1/metadata.proto\x12\x07\x62qip.v1\x1a\x14\x62qip/v1/common.proto\"\xb6\x05\n\x19InstrumentMetadataVersion\x12\x1a\n\rinstrument_id\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x1d\n\x10metadata_version\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x1e\n\x11\x65\x66\x66\x65\x63tive_from_ns\x18\x03 \x01(\x03H\x02\x88\x01\x01\x12\x1c\n\x0f\x65\x66\x66\x65\x63tive_to_ns\x18\x04 \x01(\x03H\x03\x88\x01\x01\x12\x1a\n\rknown_from_ns\x18\x05 \x01(\x03H\x04\x88\x01\x01\x12\x18\n\x0bknown_to_ns\x18\x06 \x01(\x03H\x05\x88\x01\x01\x12\x1f\n\x12supersedes_version\x18\x07 \x01(\tH\x06\x88\x01\x01\x12\x32\n\x13\x63ontract_multiplier\x18\x08 \x01(\x0b\x32\x15.bqip.v1.DecimalValue\x12\x1a\n\rquantity_unit\x18\t \x01(\tH\x07\x88\x01\x01\x12(\n\ttick_size\x18\n \x01(\x0b\x32\x15.bqip.v1.DecimalValue\x12\'\n\x08lot_size\x18\x0b \x01(\x0b\x32\x15.bqip.v1.DecimalValue\x12\x19\n\x0cproduct_type\x18\x0c \x01(\tH\x08\x88\x01\x01\x12\x19\n\x0cmargin_asset\x18\r \x01(\tH\t\x88\x01\x01\x12\x1d\n\x10settlement_asset\x18\x0e \x01(\tH\n\x88\x01\x01\x42\x10\n\x0e_instrument_idB\x13\n\x11_metadata_versionB\x14\n\x12_effective_from_nsB\x12\n\x10_effective_to_nsB\x10\n\x0e_known_from_nsB\x0e\n\x0c_known_to_nsB\x15\n\x13_supersedes_versionB\x10\n\x0e_quantity_unitB\x0f\n\r_product_typeB\x0f\n\r_margin_assetB\x13\n\x11_settlement_assetb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bqip.v1.metadata_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INSTRUMENTMETADATAVERSION']._serialized_start=58
  _globals['_INSTRUMENTMETADATAVERSION']._serialized_end=752
# @@protoc_insertion_point(module_scope)
