# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bqip/v1/source.proto
# Protobuf Python Version: 6.33.6
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    6,
    '',
    'bqip/v1/source.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from bqip.v1 import common_pb2 as bqip_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x62qip/v1/source.proto\x12\x07\x62qip.v1\x1a\x14\x62qip/v1/common.proto\"\x93\x02\n\rSourceLineage\x12\x1d\n\x10venue_profile_id\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x1f\n\x12venue_profile_hash\x18\x02 \x01(\x0cH\x01\x88\x01\x01\x12&\n\ncapture_id\x18\x03 \x01(\x0b\x32\x12.bqip.v1.CaptureId\x12\x1d\n\x10raw_content_hash\x18\x04 \x01(\x0cH\x02\x88\x01\x01\x12!\n\x14receive_timestamp_ns\x18\x05 \x01(\x03H\x03\x88\x01\x01\x42\x13\n\x11_venue_profile_idB\x15\n\x13_venue_profile_hashB\x13\n\x11_raw_content_hashB\x17\n\x15_receive_timestamp_ns\"J\n\x0eQueryParameter\x12\x11\n\x04name\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x12\n\x05value\x18\x02 \x01(\tH\x01\x88\x01\x01\x42\x07\n\x05_nameB\x08\n\x06_value\"\x9d\x02\n\x11HttpSourceContext\x12\'\n\x07lineage\x18\x01 \x01(\x0b\x32\x16.bqip.v1.SourceLineage\x12\x30\n\ttransport\x18\x02 \x01(\x0e\x32\x18.bqip.v1.SourceTransportH\x00\x88\x01\x01\x12\x13\n\x06method\x18\x03 \x01(\tH\x01\x88\x01\x01\x12\x15\n\x08\x65ndpoint\x18\x04 \x01(\tH\x02\x88\x01\x01\x12\x31\n\x10query_parameters\x18\x05 \x03(\x0b\x32\x17.bqip.v1.QueryParameter\x12\x18\n\x0bhttp_status\x18\x06 \x01(\rH\x03\x88\x01\x01\x42\x0c\n\n_transportB\t\n\x07_methodB\x0b\n\t_endpointB\x0e\n\x0c_http_status\"\xfe\x01\n\x13StreamSourceContext\x12\'\n\x07lineage\x18\x01 \x01(\x0b\x32\x16.bqip.v1.SourceLineage\x12\x30\n\ttransport\x18\x02 \x01(\x0e\x32\x18.bqip.v1.SourceTransportH\x00\x88\x01\x01\x12\x15\n\x08\x65ndpoint\x18\x03 \x01(\tH\x01\x88\x01\x01\x12\x14\n\x07\x63hannel\x18\x04 \x01(\tH\x02\x88\x01\x01\x12 \n\x13original_session_id\x18\x05 \x01(\x0cH\x03\x88\x01\x01\x42\x0c\n\n_transportB\x0b\n\t_endpointB\n\n\x08_channelB\x16\n\x14_original_session_id*s\n\x0fSourceTransport\x12 \n\x1cSOURCE_TRANSPORT_UNSPECIFIED\x10\x00\x12\x1e\n\x1aSOURCE_TRANSPORT_HTTP_REST\x10\x01\x12\x1e\n\x1aSOURCE_TRANSPORT_WEBSOCKET\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bqip.v1.source_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SOURCETRANSPORT']._serialized_start=954
  _globals['_SOURCETRANSPORT']._serialized_end=1069
  _globals['_SOURCELINEAGE']._serialized_start=56
  _globals['_SOURCELINEAGE']._serialized_end=331
  _globals['_QUERYPARAMETER']._serialized_start=333
  _globals['_QUERYPARAMETER']._serialized_end=407
  _globals['_HTTPSOURCECONTEXT']._serialized_start=410
  _globals['_HTTPSOURCECONTEXT']._serialized_end=695
  _globals['_STREAMSOURCECONTEXT']._serialized_start=698
  _globals['_STREAMSOURCECONTEXT']._serialized_end=952
# @@protoc_insertion_point(module_scope)
